### ISSUE TITLE
Do you know if it's possible (even with forking this plugin) if I can have a background color when there is an error ?

### ISSUE THREAD

**Issue by SirMishaa** [chylex/IntelliJ-Inspection-Lens#13]
Hello, 

First of all, thank you very much for your plugin, it is very useful.
Nevertheless, I'm trying to get the same rendering as this one: 

![image](https://user-images.githubusercontent.com/42717232/230811904-15a2e89d-832b-4300-8349-8ed933bbb0f4.png)

The aim is to have the whole line with a background color to highlight the problematic line in case of an error/warning.
Do you know if this is natively feasible? Or if you think that by forking / making a PR, I can achieve this result? 

Thank you very much.

**Comment by chylex** [comment]
Anything is possible, but I don't know any of the APIs for coloring line background off the top of my head. When you place the caret on a line, IntelliJ already highlights the whole line with a special background color, so that might be a good place to start looking for the APIs.

I think it would be a nice feature for the plugin, as long as it behaves correctly if there are multiple inspections on the same line, and more importantly, the performance impact of the feature is minimal even with a huge file with thousands of inspections.

**Comment by chylex** [comment]
Since a new issue was opened with discussion of the implementation, I'm closing this in favor of #14.
