### ISSUE TITLE
Color configuration

### ISSUE THREAD

**Issue by synopss** [chylex/IntelliJ-Inspection-Lens#19]
The idea is to start creating configuration for the plugin.
Best way to start : Color customization.

I've worked on a poc already, it will need to rethink the color system by using TextAttributesKeys configurable with xml files.

![image](https://github.com/chylex/IntelliJ-Inspection-Lens/assets/15261768/947b3a8e-cd9e-40de-a214-bbeae534a5f2)

For now, nothing is linked to the plugin, it's just some UI work.
See : https://github.com/synopss/IntelliJ-Inspection-Lens/tree/feat/settings

**Comment by chylex** [comment]
I thought about it and with the background line colors I made the call to not add customization, primarily because every single thing that's in this plugin becomes my responsibility to not only test - which gets tricky with customization options - but also be expected to maintain basically forever... so for now, any customization is probably best left for a community fork.

**Comment by synopss** [comment]
Understandable, I'll stop there then. I'll keep the fork open so you change your mind, you'll have some kind of basis if you need one.

**Comment by DAmNRelentless** [comment]
Forget what I said synopss. But I'd really like to use your fork with the customization option then. Would you publish a release on it so I don't have to build it myself? :)

**Comment by chylex** [comment]
I'm wondering what is the reason for wanting color customization in the first place, because besides just wanting it, specific problems such as

- "I customized the colors in 'Color Scheme - Errors and Warnings' and now the default colors in the plugin don't match" or
- "The plugin doesn't work well with a high contrast theme"

can be solved without the users having to customize every color in the plugin.

**Comment by synopss** [comment]
I agree that it’s not particularly important. My perspective is simple: some people enjoy customizing things. Is it mandatory? Definitely not. Is it a nice-to-have? Probably.

As you pointed out, allowing customization might lead to users choosing odd color combinations, but that’s not really the plugin’s responsibility.

**Comment by chylex** [comment]
You can already customize colors of error stripe marks or underlines for both standard and user-defined inspections though, to me it would make more sense for the plugin to adapt to those colors instead.

I have started an experiment in that area, not sure if/when I'll have any results.
