### ISSUE TITLE
Allow to configure verbosity

### ISSUE THREAD

**Issue by haringsrob** [chylex/IntelliJ-Inspection-Lens#2]
Works great, would be cool if we could set it to only show warnings/errors for example.

**Comment by chylex** [comment]
I'll consider it. As it says in the description, this plugin has no customization; generally I find IntelliJ's configuration system to be a hassle, but I can see this being useful.

**Comment by HudsonAfonso** [comment]
Could the plugin use the same font as the code?

**Comment by chylex** [comment]
> Could the plugin use the same font as the code?

Please don't post off-topic questions in someone else's issue, use https://github.com/chylex/IntelliJ-Inspection-Lens/discussions instead.

**Comment by sven-meyer-wetter-com** [comment]
This would actually be very nice. Or at least show errors before warnings from left to right. For example, when having both an ESLint warning and a Typescript error in one line, the ESLint warning is displayed before the actual TS error (which is also causing this ESLint warning).

**Comment by chylex** [comment]
> This would actually be very nice. Or at least show errors before warnings from left to right. For example, when having both an ESLint warning and a Typescript error in one line, the ESLint warning is displayed before the actual TS error (which is causing this ESLint warning).

Highlights are sorted by the position on the line, but if two highlights are on the same position - which sounds like that might be your case - then there is no tie-breaker and it would make sense to always prioritize higher severity.

I can improve that in the next update. An example to clarify:

![obrazek](https://user-images.githubusercontent.com/3685160/210684765-805aa15e-a1bd-4b48-a0f2-b48c55cdcfe3.png)

There are two positions with two highlights each: the field name and the number literal.

The field name has a warning and typo, so the warning will appear before the typo. The number literal has an error and weak warning, so the error will appear before the weak warning, but both will appear after the field name's highlights because the number literal is further on the line.
