### ISSUE TITLE
Allow using tooltip's font instead of editor's font

### ISSUE THREAD

**Issue by lppedd** [chylex/IntelliJ-Inspection-Lens#23]
Sometimes using the monospaced editor's font means longer messages, up to being impossible to read.  
Using the tooltip's font will result in more compact inlays.

**Comment by judison** [comment]
The monospaced font made it somewhat indistinguishable from the code.
I think user Ippedd means the visual like "usages" one in this screen:
![image](https://github.com/user-attachments/assets/aaa73c11-5645-4cf0-a23e-a44b292cc349)
I'm not sure, but..., a little bit smaller, maybe?

Another great thing would be make it clickable, opening the context actions on the error/warn message

**Comment by chylex** [comment]
The problem I have is that the UI font ends up vertically misaligned, which is ugly and distracting, and it looks like too much work to fix just for Inspection Lens inlays. There is no way to customize just the inlay font either. I think I'd rather report this to JB to improve first.

**Comment by chylex** [comment]
> Another great thing would be make it clickable, opening the context actions on the error/warn message

I looked into this a while back with no luck, but I tried again and I have a prototype, but it needs access to private IntelliJ APIs.

**Comment by lppedd** [comment]
@chylex if it can reassure you, I've been using internal APIs for some hacks in my plugins since 2019, with minor adjustments during the years.

Regarding the tooltip font, as far as I know the vertical alignment on the editor's line is done automatically in recent releases. Worth a try imo.

**Comment by chylex** [comment]
The APIs I'm talking about are not internal, they are private.

The text baseline is aligned between the editor and inlay, but only because Inspection Lens already shifts it by one pixel. This is how it would look with UI font without any baseline adjustment:

![image](https://github.com/user-attachments/assets/3c31cee1-8040-4569-b06f-1a4f76576e0e)

Another issue is that the inlay font is always 1 size smaller. Depending on which fonts you use, that can range from ugly to unreadable; in Rider specifically, Code Vision inlays are so bad I opened an issue specifically for that.

**Comment by chylex** [comment]
With the baseline adjustment, the UI font doesn't look half-bad, but that's just on one computer with Windows fonts. I've seen rendering get wonky on high DPI monitors, especially Mac OS with Retina screens, and needed ugly workarounds for that in another project.
